Package-A/main/default/objects/Employee__c/fields/Annual_Balance_Leave__c.field-meta.xml
<CustomField>
    <fullName>Annual_Balance_Leave__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Annual Balance Leave</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Package-A/main/default/objects/Employee__c/fields/Balance_Leave__c.field-meta.xml
<CustomField>
    <fullName>Balance_Leave__c</fullName>
    <formula>IF(First_Day_Of_Month__c == Joining_Date__c, ((YEAR(TODAY()) - YEAR(Joining_Date__c) - 1) *12) + (12 - MONTH(Joining_Date__c) +1) + MONTH(TODAY())
, ((YEAR(TODAY()) - YEAR(Joining_Date__c) - 1) *12) + (12 - MONTH(Joining_Date__c) +1) + MONTH(TODAY())
- 1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance Leave</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Package-A/main/default/objects/Employee__c/fields/First_Day_Of_Month__c.field-meta.xml
<CustomField>
    <fullName>First_Day_Of_Month__c</fullName>
    <formula>DATE(
     YEAR(Joining_Date__c),
     MONTH(Joining_Date__c),
     1
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>First Day Of Month</label>
    <type>Date</type>
</CustomField>

Package-A/main/default/objects/Employee__c/fields/Leave_Applied__c.field-meta.xml
<CustomField>
    <fullName>Leave_Applied__c</fullName>
    <label>Leave Applied</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EmployeeLeave.cls
public class EmployeeLeave {
    public Employee__c emp{get;set;}
    public Integer leaveDay{get;set;}
    
    public EmployeeLeave(){
        emp = [select id,First_Day_Of_Month__c,Joining_Date__c,Annual_Balance_Leave__c,Balance_Leave__c,Leave_Applied__c
               from Employee__c limit 1];
    }
    
    public static void calculateLeave(){
       /* system.debug('emp'+emp);
        
        emp.Annual_Balance_Leave__c =  emp.Balance_Leave__c - emp.Leave_Applied__c - leaveDay;
        system.debug(' emp.Annual_Balance_Leave__c'+ emp.Annual_Balance_Leave__c);

        emp.Leave_Applied__c = leaveDay;
        system.debug(' emp.Leave_Applied__c'+  emp.Leave_Applied__c);
        
     
        update emp;  */
    }
}